name: Deploy to Server

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #      - name: Setup Bun
      #        uses: oven-sh/setup-bun@v2.1.0
      #        with:
      #          bun-version: latest

      - name: Install dependencies
        run: |
          bun install
          bun install --os=linux --cpu=x64 sharp

      - name: Generate SvelteKit files
        run: bunx svelte-kit sync

      - name: Build application
        run: bun run build

      - name: Paste files to right location
        run: |
          cd ~/portail-etu
          # Remove all files except .env
          find . -mindepth 1 -maxdepth 1 -not -name ".env" -exec rm -rf {} +
          cp ~/actions-runner/_work/refonte-portail-etu/refonte-portail-etu/* . -r

      - name: Restart server
        run: |
          pm2 restart ./ecosystem.config.cjs --update-env || pm2 start ./ecosystem.config.cjs
